name: Validation

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    name: meta-kanto Build
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Free space info
        run: |
          echo "Free space:"
          df -h
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: meta-kanto
      - name: Clone poky
        run: git clone -b kirkstone git://git.yoctoproject.org/poky
      - name: Clone meta-openembedded
        run: git clone -b kirkstone https://github.com/openembedded/meta-openembedded.git
      - name: Clone meta-virtualization
        run: git clone -b kirkstone https://github.com/lgirdk/meta-virtualization.git
      - name: Add dependencies
        run: |
          sudo apt-get update
          sudo apt-get install diffstat
      - name: Initialize build
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-oe
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake-layers add-layer ../meta-openembedded/meta-networking
          bitbake-layers add-layer ../meta-openembedded/meta-filesystems
          bitbake-layers add-layer ../meta-virtualization
          bitbake-layers add-layer ../meta-kanto
      - name: Build suite connector
        run: |
          source poky/oe-init-build-env build
          bitbake suite-connector
      - name: Build bootstrapping
        run: |
          source poky/oe-init-build-env build
          bitbake suite-bootstrapping
      - name: Build local digital twins
        run: |
          source poky/oe-init-build-env build
          bitbake local-digital-twins
      - name: Build file backup
        run: |
          source poky/oe-init-build-env build
          bitbake file-backup
      - name: Build file upload
        run: |
          source poky/oe-init-build-env build
          bitbake file-upload
      - name: Build software update
        run: |
          source poky/oe-init-build-env build
          bitbake software-update
      - name: Build system metrics
        run: |
          source poky/oe-init-build-env build
          bitbake system-metrics
      - name: Build container management
        run: |
          source poky/oe-init-build-env build
          bitbake container-management
      - name: Free space info
        run: |
          echo "Free space:"
          df -h